name: SCAD production

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  packages: read

jobs:
  scad:
    uses: brainboxemb/tool.scad-project/.github/workflows/project-production.yml@da57820fdadd7d203091b6818984991f1548408f
    with:
      affected_task: consumer:scad.production-impact
      aggregate_task: consumer:scad.ci
      cache_namespace: lib-scad-clamps-production-v1
      build_artifact_name: lib-scad-clamps-build-publication
      verification_artifact_name: lib-scad-clamps-verification-publication
